FROM node:18 AS Build

WORKDIR /usr/src/app

COPY ./project .

RUN npm install

RUN npm run build

FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/dist/project /usr/share/nginx/html
