version: '3.9'

services:
  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - 8082:4200
    volumes:
      - ./frontend/project:/usr/src/app
